### PR TITLE
Feat: add ctrl + s functionality for saving the file

### PR DESCRIPTION
**Pull request by whyang0808**
# Issue #7

### Changes
- feat: add ctrl + s functionality for saving the file.

### CODE REVIEW

**Review by hypermystic — APPROVED** [review]
LGTM!

**Comment by hypermystic** [comment]
Thanks for implementing this @whyang0808, https://github.com/hypermystic/bookit/commit/3117ae5890a7f07366caa754bac85c9ce9df83a6
did a small fix so that it will overwrite the ctrl+s inbuilt functionality.

**Comment by whyang0808** [comment]
> Thanks for implementing this @whyang0808, [3117ae5](https://github.com/hypermystic/bookit/commit/3117ae5890a7f07366caa754bac85c9ce9df83a6)
> did a small fix so that it will overwrite the ctrl+s inbuilt functionality.

You're welcome @hypermystic 
Seems like the `KeyboardEvent.keyCode` is deprecated: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode. Perhaps can use `code` or `key`.

**Comment by vaibhav111tandon** [comment]
Oops... haven't seen that...now I have to go for a fix again... thanks @whyang0808

**Comment by vaibhav111tandon** [comment]
@hypermystic seems that you have to go for a fix again..thanks @whyang0808

**Pull request merged**
